/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package qlnx_gui;
import java.io.InputStream;
import java.util.ArrayList;
import qlnx_dao.*;
import qlnx_pojo.*;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.util.*;


/**
 *
 * @author phatnguyen
 */
public class VeXe extends javax.swing.JFrame {
    OracleSeverProvider db = new OracleSeverProvider();
    private String username;
   

    /**
     * Creates new form VeXe
     */
    public VeXe(String user) throws ParseException {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Vé Xe");
        this.username = user;
        db.open();
        DefaultTableModel dtmVX = (DefaultTableModel)tblVeXe.getModel();
        String [] tieude = {"Mã Vé", "Tên Nhân Viên", "Tên Chuyến", "Tên Khách Hàng", "Ngày Đi", "Vị Trí", "Giá Vé"};
        dtmVX.setColumnIdentifiers(tieude);
        load_vx();
        load_cx();
        load_kh();
        load_Vitri();
    }

    private VeXe() {
        
    }
    private void load_vx(){
        try {
            DefaultTableModel dtmVX = (DefaultTableModel)tblVeXe.getModel();
            SimpleDateFormat intput = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            SimpleDateFormat output = new SimpleDateFormat("dd-MM-y");
            ArrayList <VeXePoJo> dsVX = VeXeDAO.layDanhSachVX();
            dtmVX.setRowCount(0);
            for(VeXePoJo vx : dsVX){
                Vector<Object> vec = new Vector<Object>();
                String ngayDiIn = vx.getNgayDi();
                Date d  = intput.parse(ngayDiIn);
                String ngayDiout = output.format(d);
                vec.add(vx.getMaVe());
                vec.add(vx.getMaNV());
                vec.add(vx.getMaChuyen());
                vec.add(vx.getMaKH());
                vec.add(ngayDiout);
                vec.add(vx.getViTri());
                vec.add(vx.getGiaVe());
                dtmVX.addRow(vec);
        }  
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error"+e);
        }
     
    }
    private void load_cx(){
        cbxChuyenXe.removeAllItems();
        try {
            ResultSet rs = db.excuteQuery("select tenchuyen from chuyenxe");
            while(rs.next()){
                cbxChuyenXe.addItem(rs.getString("tenchuyen"));
            }
        } catch (Exception e) {
        }
    }
    private void load_kh(){
        cbxKhachHang.removeAllItems();
        try {
            ResultSet rs = db.excuteQuery("select tenkh from khachhang");
            while(rs.next()){
                cbxKhachHang.addItem(rs.getString("tenkh"));
            }
        } catch (Exception e) {
        }
    }
    private void load_Vitri(){
        cbxViTRi.removeAllItems();
        String [] gioXP = {"A1","A2","A3","A4","A5","B1","B2","B3","B4","B5","C1","C2","C3","C4","C5","D1","D2","D3","D4","D5"};
        for(String items : gioXP){
            cbxViTRi.addItem(items);
            
        }
    }
    private void closeForm() {
        dispose(); // đóng form hiện tại
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel3 = new javax.swing.JLabel();
        dateNgayDi = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        cbxChuyenXe = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtGiaVe = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblVeXe = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        cbxViTRi = new javax.swing.JComboBox<>();
        btnIn = new com.k33ptoo.components.KButton();
        btnThem = new com.k33ptoo.components.KButton();
        btnXoa = new com.k33ptoo.components.KButton();
        btnSua = new com.k33ptoo.components.KButton();
        btnTimf = new com.k33ptoo.components.KButton();
        jLabel8 = new javax.swing.JLabel();
        cbxKhachHang = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtMaVe = new javax.swing.JTextField();
        btnThoat = new com.k33ptoo.components.KButton();
        btnIn2 = new com.k33ptoo.components.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 255, 255));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("THÔNG TIN VÉ XE");

        dateNgayDi.setDateFormatString("dd-MM-y");
        dateNgayDi.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NGÀY ĐI");

        cbxChuyenXe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("GIÁ VÉ");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("CHUYẾN XE");

        txtGiaVe.setBackground(new java.awt.Color(0, 255, 255));
        txtGiaVe.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtGiaVe.setForeground(new java.awt.Color(51, 51, 51));
        txtGiaVe.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 51, 204)));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tblVeXe.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tblVeXe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblVeXe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVeXeMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblVeXe);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("VỊ TRÍ");

        cbxViTRi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnIn.setText("IN DOANH THU");
        btnIn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnIn.setkBorderRadius(36);
        btnIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInActionPerformed(evt);
            }
        });

        btnThem.setText("ĐẶT VÉ");
        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnThem.setkBorderRadius(36);
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setText("XÓA");
        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnXoa.setkBorderRadius(36);
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setText("SỬA");
        btnSua.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnSua.setkBorderRadius(36);
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnTimf.setText("TÌM");
        btnTimf.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnTimf.setkBorderRadius(36);
        btnTimf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimfActionPerformed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("KHÁCH HÀNG");

        cbxKhachHang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("MÃ VÉ");

        txtMaVe.setBackground(new java.awt.Color(0, 255, 255));
        txtMaVe.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtMaVe.setForeground(new java.awt.Color(51, 51, 51));
        txtMaVe.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 51, 204)));

        btnThoat.setText("THOÁT");
        btnThoat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnThoat.setkBorderRadius(30);
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        btnIn2.setText("DOANH THU THÁNG");
        btnIn2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnIn2.setkBorderRadius(36);
        btnIn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIn2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jLabel4))
                .addGap(35, 35, 35)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateNgayDi, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxChuyenXe, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(205, 205, 205)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbxViTRi, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMaVe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtGiaVe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(69, 69, 69))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnIn, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnTimf, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(btnIn2, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cbxChuyenXe, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxViTRi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel7))
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMaVe, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(dateNgayDi, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtGiaVe, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63)))
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInActionPerformed
       // TODO add your handling code here:
       String txtUser = this.username;
       if(txtUser.equals("admin")){
           VeXeDAO vx = new VeXeDAO();    
           ArrayList <VeXePoJoRePort> dsVX = VeXeDAO.layDanhSachVX1();
           vx.InDoanhThu(dsVX);
       }
       else {
           JOptionPane.showMessageDialog(this, "Bạn không có quyền truy cập");
       } 

       
    }//GEN-LAST:event_btnInActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        try {
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");     
            VeXePoJo vx = new VeXePoJo();
            Date ngayHienTai = new Date ();
            Date ngayDii = dateNgayDi.getDate();
            if(ngayDii.compareTo(ngayHienTai)>=0){
                String ngayDi = dateFormat.format(ngayDii);  
                vx.setMaKH(cbxKhachHang.getSelectedItem().toString());
                vx.setMaChuyen(cbxChuyenXe.getSelectedItem().toString());
                vx.setNgayDi(ngayDi);
                vx.setViTri(cbxViTRi.getSelectedItem().toString());
                vx.setMaNV(this.username);
                vx.setGiaVe(Float.parseFloat(txtGiaVe.getText()));
                VeXeDAO.datVe(vx);
                load_vx();
            }
                        else{
                JOptionPane.showMessageDialog(this, "Ngày đi phải lớn hơn bằng ngày hiện tại");
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Không thể đặt vé");
        }                 
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        String maVe = txtMaVe.getText();
        VeXeDAO.xoaVe(maVe);
        load_vx();
        
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        try {
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");     
            VeXePoJo vx = new VeXePoJo();
            Date ngayHienTai = new Date ();
            Date ngayDii = dateNgayDi.getDate();
            if(ngayDii.compareTo(ngayHienTai)>=0){
                String ngayDi = dateFormat.format(ngayDii);  
                vx.setMaKH(cbxKhachHang.getSelectedItem().toString());
                vx.setMaChuyen(cbxChuyenXe.getSelectedItem().toString());
                vx.setNgayDi(ngayDi);
                vx.setViTri(cbxViTRi.getSelectedItem().toString());
                vx.setMaNV(this.username);
                vx.setGiaVe(Float.parseFloat(txtGiaVe.getText()));
                VeXeDAO.suaVe(vx);
                load_vx();
            }
            else{
                JOptionPane.showMessageDialog(this, "Ngày đi phải lớn hơn bằng ngày hiện tại");
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error"+e);
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnTimfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimfActionPerformed
        // TODO add your handling code here:
        String maVe = txtMaVe.getText();
        try {
            DefaultTableModel dtmVX = (DefaultTableModel)tblVeXe.getModel();
            SimpleDateFormat intput = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            SimpleDateFormat output = new SimpleDateFormat("dd-MM-y");
            ArrayList <VeXePoJo> dsVX = VeXeDAO.timVe(maVe);
            dtmVX.setRowCount(0);
            for(VeXePoJo vx : dsVX){
                Vector<Object> vec = new Vector<Object>();
                String ngayDiIn = vx.getNgayDi();
                Date d  = intput.parse(ngayDiIn);
                String ngayDiout = output.format(d);
                vec.add(vx.getMaVe());
                vec.add(vx.getMaNV());
                vec.add(vx.getMaChuyen());
                vec.add(vx.getMaKH());
                vec.add(ngayDiout);
                vec.add(vx.getViTri());
                vec.add(vx.getGiaVe());
                dtmVX.addRow(vec);
        }  
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error"+e);
        }
    }//GEN-LAST:event_btnTimfActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        Home home = new Home(this.username);
        home.setVisible(true);
        closeForm();
    }//GEN-LAST:event_btnThoatActionPerformed

    private void tblVeXeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVeXeMouseClicked
        // TODO add your handling code here:
        int row = tblVeXe.getSelectedRow();
        txtMaVe.setText(String.valueOf(tblVeXe.getValueAt(row, 0)));
        txtGiaVe.setText(String.valueOf(tblVeXe.getValueAt(row, 6)));
    }//GEN-LAST:event_tblVeXeMouseClicked

    private void btnIn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIn2ActionPerformed
        // TODO add your handling code here:
        String txtUser = this.username;
       if(txtUser.equals("admin")){
           VeXeDAO vx = new VeXeDAO();    
           ArrayList <VeXePoJoRePort> dsVX = VeXeDAO.DoanhThuThang();
           vx.InDoanhThuThang(dsVX);
       }
       else {
           JOptionPane.showMessageDialog(this, "Bạn không có quyền truy cập");
       } 
    }//GEN-LAST:event_btnIn2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VeXe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VeXe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VeXe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VeXe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VeXe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton btnIn;
    private com.k33ptoo.components.KButton btnIn2;
    private com.k33ptoo.components.KButton btnSua;
    private com.k33ptoo.components.KButton btnThem;
    private com.k33ptoo.components.KButton btnThoat;
    private com.k33ptoo.components.KButton btnTimf;
    private com.k33ptoo.components.KButton btnXoa;
    private javax.swing.JComboBox<String> cbxChuyenXe;
    private javax.swing.JComboBox<String> cbxKhachHang;
    private javax.swing.JComboBox<String> cbxViTRi;
    private com.toedter.calendar.JDateChooser dateNgayDi;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JTable tblVeXe;
    private javax.swing.JTextField txtGiaVe;
    private javax.swing.JTextField txtMaVe;
    // End of variables declaration//GEN-END:variables
}
